use_frameworks!

platform :ios, '8.0'

target 'XJPrefrenceTestCategoryKit_Example' do
  pod 'XJPrefrenceTestCategoryKit', :path => '../'

  target 'XJPrefrenceTestCategoryKit_Tests' do
    inherit! :search_paths

    
  end
end
